default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 3306
  username: root
  password: 12345678
  host: localhost

development:
  <<: *default
  database: "tasks_c2s_development"

test:
  <<: *default
  database: "tasks_c2s_test"


production:
  <<: *default
  # database: path/to/persistent/storage/production.sqlite3
